---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ROUTE=update_reviewer_issues_database
    volumes:
      - .:/app
    command: ["python3", "main/server/main.py"]
