---
name: build image

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - id: Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up google cloud sdk
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Grant permissions to docker
        run: gcloud auth configure-docker --quiet

      - name: Build docker image
        run: docker build -t "$IMAGE_NAME" .

      - name: Push docker image
        run: docker push $IMAGE_NAME

      - name: Deploy docker image
        run: gcloud run deploy ${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }} --project ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region ${{ secrets.GCP_REGION }} --platform managed
